sudo: false
language: python
env:
  global:
  - secure: YtzZ7Na630DH3ogAgAR4bGtja0NT+/SHLFs0jRt6XlPoxqta69vmAbUTHfGTNqaBJxoXO2ADOPOQBcjOVhZHVL0obq0nzvEFuxBVVtQFjFbeTSP51nS05vr5YOLrX2Envv4wJ81GFWL2cb6fzcXG+LwqdGBf3XqfKfy+jyyybD4TTxgq0ulOPcWLvjk3eFhjlNMfcVuIPG+98piwIKTgdFaICAF+9xDvdJquXTmzu3+VPwxnzBTFp2hR9eem3M1WGkjAQWGB4j6UAyaudAegiGQ26syX1Znl+NegvV2vB+d5gE5OgzfMaM2P27vJhLOQUXbVzuHk39q8iQhfIVmZvWxuGV7lYNvW3w/ksm9ovNpOwhx5q4j59kUY7uK8wWmvaSEALfKyuNs6+0phvAPIU4Z7XsieT8tiWszNik+Wgwdd/MPmwW9HqoRNnBSLpAXPSCmjblMKKsf360a9JP0Yf0zmbjuA7Twd+fsQP5SY+QuVMCFhWhilPJLtqYtn7bv70dnzRvdqERMN0xUpWf6MUZ/h6M44m0T0o0jtV2s3dSwGb/2BPyPJNdSJ6qqKtkDcJMdWPmiRPiCYaRuxSzTMw8qMNzJmjLcGSW3tZE5zl4/uMlblThiogNLYvw9u6IUkvBww6kxBm4RLsSxEP3EzaIE0HmU/W5cr0Bf9HRe5dXc=
install:
  - pip3 install --upgrade pip
script:
  - "./test.sh"
  - "./build.sh"
deploy:
  - provider: pypi
    skip_cleanup: true
    user: bigclownlabs
    password:
      secure: hoXYSZL/MPjID4TVGZ3CQAVDe4Ef0vdiFB1IaRm0d/CboVMYXWb/wuZZKBpoOkBGpK0f39UZ7pkPsndBzfysIPlqKX4S1AsAvXMpGJhppKQvxCUXG7QayhxD1jILlgLkQeGf/67H7b7rvrr4l2Z2i4i3vcVciv6dzo1qvSHS6jNA4yJijU5RxCSIWR7ZCirkIWsCiYkk4TAUup8TG2zv9RGFs4Xkl97pKkDjbnsaPxnFFVedA6t+bbNWUwPFrofRSMf0ovObyPTLP94QTEW1qvOXwCtNKw9SRvbwxmzT1578CLXDczB8byuKdnqpX3pNobZ3M1BTyYPkoU/gBkJCLqoj2dspRC6qL2JRMYiqh4xtmATsJI5PFwQZXCECn1fPVeSA3tW3uAoDbC8NSMHLw6XHTzsfYtREhYPu4NOfVM+4W8zmZl9ktPH0V8ixv5MatCc7z0nBTkFCd8zy5kqqbHVXmlPyCcdVcx7sGZAFLh83iPh9xJlv4fhxYXjWKisILdeBrQlAKkkwZaNTnroNY0NoYb3XAhjtVmg1OEihr8VYoDUaRilhFMxRougJOlcU92iVZ+XVvIzT4wYVl9euTRf7ShwyIKGHTXvMLy4QbaSByUe2q/ABtWU//9oW8Wq5oih/hX+ZVgZcYz39oU4v2hWkLkyG0H+7fs1k53VgIrU=
    on:
      tags: true
